language: "perl"
perl:
    - "5.6"
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "blead"
before_install:
    - git clone git://github.com/haarg/perl-travis-helper
    - source perl-travis-helper/init
    - build-perl
    - perl -V
install:
    - export AUTOMATED_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
before_script:
    - cpanm -n Devel::Cover::Report::Coveralls
script:
    perl Makefile.PL && make && cover -test -report coveralls

notifications:
  email:
    on_success: change
    on_failure: always

# fast_finish: http://blog.travis-ci.com/2013-11-27-fast-finishing-builds/
matrix:
  fast_finish: true
  allow_failures:
    - perl: "5.6"
    - perl: "5.20"
    - perl: "blead"
# unknown to perlbrew at travis. ERROR: The installation "5.20" is unknown.

# Hack to not run on tag pushes:
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
